# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='MIT'

[[mods]]
modId="gasgas"
version="${file.jarVersion}"
displayName="Gas! Gas! Gas!"
#logoFile="icon.png"
credits=""
authors="LubieKakao1212"
description='''
More realistic gas mechanics
'''
[[dependencies.gasgas]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gasgas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19)"
    ordering="NONE"
    side="BOTH"
